# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 214d4be5a907b7d70bda04e220594472cc4ccdc6f508ea8535193841dad4e62ef1c441119ef96caa4ccc3827266a6b1ed17f99b472f9d3f0446d8bee18431bd6

test:
  secret_key_base: feccac50f7c519fbba32fe85b1e7863ebea8ce25b1aa925e8c08dc619127b6b5c5786c514cb4d8a91fb942b658456a21f98b1892b8ed7707cc94c8ea587dee45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
